services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    ports:
      - "127.0.0.1:39670:80"
    environment:
      CRON_MIN: '*/13'
      TZ: America/Chicago
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
    restart: unless-stopped

volumes:
  freshrss_data:
  freshrss_extensions:
